# Makefile for MemDripper
# Copyright (c) 2012,2013 Sony Corporation
#

memdripper-objs	:= memdump.o memdump_trigger.o memdump_fwrite.o memdump_proc.o memdump_pte.o

obj-$(CONFIG_SNSC_MEMDRIPPER)	+= memdripper.o
